name: Prevent Supabase Pause

on:
  schedule:
    # Runs at 09:00 UTC on Monday and Thursday
    # Pazartesi ve Perşembe günleri saat 09:00'da çalışır
    - cron: '0 9 * * 1,4'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET 'https://nlgmojnbkethwirgmpwh.supabase.co/rest/v1/products?select=id&limit=1' \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ21vam5ia2V0aHdpcmdtcHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjQ1ODEsImV4cCI6MjA3MzUwMDU4MX0.j_vBJrDalubGqlOGT3zLyIKf6LAJ_I5N5MPjEe2MwA0" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZ21vam5ia2V0aHdpcmdtcHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjQ1ODEsImV4cCI6MjA3MzUwMDU4MX0.j_vBJrDalubGqlOGT3zLyIKf6LAJ_I5N5MPjEe2MwA0"